### ISSUE TITLE
Server hanging when upload file fails

### ISSUE THREAD

**Issue by itsmevitinn** [gsistelos/webserv#43]
when we got the error message below, the server hang.

Traceback (most recent call last):
  File "/Users/vitor/Documents/Estudos/42/Github/webserv/cgi-bin/upload.py", line 9, in <module>
    fileitem = form['filename']
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/cgi.py", line 525, in __getitem__
    raise KeyError(key)
KeyError: 'filename'

probably we are gettin this error because we are receiving a request without content, so the script will try to find a form 'filename' but doesnt exist

**Comment by itsmevitinn** [comment]
the error regarding an POST request without body was already fixed in the past, but some miscommunication happened and we forgot it.
